# å…¬é–‹ã™ã‚‹ãƒšãƒ¼ã‚¸ã®URL
baseURL = "https://SeanWakasugi.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ãƒ–ãƒ­ã‚°ã®ã‚¿ã‚¤ãƒˆãƒ«
title = "ã—ã‚‡ã€œã‚“ã®æŠ€è¡“ãƒ¡ãƒ¢ğŸ˜—"
theme = "mainroad"
paginate = 20

# è‡ªå·±ç´¹ä»‹
[Author]
    avatar = "img/avatar.jpg"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ãƒšãƒ¼ã‚¸ã®ãƒ†ãƒ¼ãƒã‚«ãƒ©ãƒ¼
[Params.style.vars]
  highlightColor = "#00bfff"

# SNSç­‰ã®ãƒ¦ãƒ¼ã‚¶ãƒ¼å
[Params.widgets.social]


[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

